### ISSUE TITLE
F-I03021 Registro de Compras Generales 

### ISSUE THREAD

**Issue by mMartinezRi** [NextSolutionsCUU/NextSolution#10]
En la ventana de campos no esta en el tamaño adecuado, debido a que el usuario puede mover los campos al tamaño que desea. 
 
![image](https://user-images.githubusercontent.com/29786357/27746231-9f223242-5d83-11e7-9da1-42919438f5f7.png)

**Comment by aMartinezRi** [comment]
si se pueden mover, como el cliente quiera
