### ISSUE TITLE
F-I01051 Registro de Área de Actividades

### ISSUE THREAD

**Issue by mMartinezRi** [NextSolutionsCUU/NextSolution#2]
¿Como elimino o edito una actividad registrada?.

**Comment by jm4rt1n3z** [comment]
Las etiquetas "Labels" ayudan a distiguir mas facil y rapido que tipo de defecto (issues) son cada uno. Ustedes pueden dar de alta alguno nuevo o traducirlos al español.
question-pregunta
bug-defecto
duplicate-duplicado
enhancement-mejora
help wanted-buscar ayuda
invalid-invalido
wontfix-no arreglaré

Esto queda abierto para que vean ustedes de que forma les gustaria entenderse entre el desarrollador (programador) y el tester (probador). 

*Tambien importante señalar de que proyecto es este error porque en un futuro pueden estar verificando varios proyectos a la vez y no sabran que defecto pertenece a que proyecto. ;-)

Una vez que quede resuelto el defecto y/o problema (issue) deben cerrar el issue (Close issue), lo correcto es que el tester (probador) lo haga pues es el que debe comprobar que se haya realizado el cambio.
