### ISSUE TITLE
F-P011011 Registro de Usuarios

### ISSUE THREAD

**Issue by jm4rt1n3z** [NextSolutionsCUU/NextSolution#30]
1.  Existe el campo NIVEL pero no tiene ninguna opción que se pueda elegir.

![image](https://user-images.githubusercontent.com/9052103/28295798-1a1d20bc-6b29-11e7-9411-ca412d0f7ec7.png)

2.  Las opciones del ESTATUS considero que deberían ser ACTIVO e INACTIVO en lugar de BAJA.

![image](https://user-images.githubusercontent.com/9052103/28295852-90a87dee-6b29-11e7-9e9e-1f9078c29f91.png)

**Comment by mMartinezRi** [comment]
El primero ya esta corregido, el segundo esta en proceso
