### ISSUE TITLE
F-P011011 Registro de Usuarios

### ISSUE THREAD

**Issue by jm4rt1n3z** [NextSolutionsCUU/NextSolution#31]
¿El cuadro dentro de la ventana es para mostrar una foto/imagen?
¿Como puedo subirla?
¿Es necesaria?
¿Donde mas es usada y/o mostrada esa imagen?

![image](https://user-images.githubusercontent.com/9052103/28295948-5f273d0e-6b2a-11e7-8e5b-05be23766184.png)

**Comment by mMartinezRi** [comment]
Lo de la foto ya se quito.
