### ISSUE TITLE
F-I06201  REGISTRO DE GASTOS ADICIONALES 

### ISSUE THREAD

**Issue by mMartinezRi** [NextSolutionsCUU/NextSolution#37]
AL MOMENTO DE GUARDAR UN REGISTRO MARCA EL SIGUIENTE ERROR.

![image](https://user-images.githubusercontent.com/29786357/28430256-09bff3a0-6d3d-11e7-92c5-dcc067955a25.png)

**Comment by gMartinezG** [comment]
SOLUCIONADO
