### ISSUE TITLE
F-P02101 REGISTRO DE TRANSFORMACION Y/O PRODUCCION 

### ISSUE THREAD

**Issue by mMartinezRi** [NextSolutionsCUU/NextSolution#38]
CAMBIAR LA REDACCIÓN DEL MENSAJE INDICANDO QUE NO SE PUEDE UTILIZAR ESE PRODUCTO PORQUE NO TIENE REGISTRADO UNA FORMULA

![image](https://user-images.githubusercontent.com/29786357/28430768-f440f996-6d3e-11e7-8a4a-670e04d14dc3.png)
![image](https://user-images.githubusercontent.com/29786357/28430774-f74b5ffa-6d3e-11e7-8d25-d1c74031d9a1.png)

**Comment by gMartinezG** [comment]
solucionado
