### ISSUE TITLE
F-I03011 Registro de Entradas de Almacén

### ISSUE THREAD

**Issue by mMartinezRi** [NextSolutionsCUU/NextSolution#7]
Cuando empiezo a realizar movimientos dentro de la ventana se bloquean las imágenes de “Borrar” e “imprimir” de… ![image](https://user-images.githubusercontent.com/29786357/27746057-00795184-5d83-11e7-80a2-d2c6b2eebd4d.png)  a… 
![image](https://user-images.githubusercontent.com/29786357/27746084-111f1a50-5d83-11e7-9ddd-8267284a7511.png)

**Comment by aMartinezRi** [comment]
orale, y luego?
